#!/bin/zsh

export PATH="$PATH:$HOME/.config/scripts"

# TMUX session handling
if [ -z "$TMUX" ]; then
    tmux attach -t TMUX || tmux new -s TMUX
fi

# zsh-autosuggestions
if [ ! -d "$HOME/.zsh/zsh-autosuggestions" ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions $HOME/.zsh/zsh-autosuggestions
fi
source $HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# Bind key for autosuggestions
bindkey '^ ' autosuggest-accept


bindkey -s ^f "tmux-fzf-window\n"

# Command history settings
HISTSIZE=5000                 # Set maximum number of lines in history
HISTFILE=~/.zsh_history       # Define the location of the history file
SAVEHIST=5000                 # Save 5000 lines of history to the file
HISTDUP=erase                 # Remove duplicates in history
setopt appendhistory          # Append new history lines to the history file
setopt sharehistory           # Share history among all sessions
setopt incappendhistory       # Immediately append new lines to the history file
setopt hist_ignore_all_dups   # Ignore all duplicated commands in history
setopt hist_save_no_dups      # Save only the most recent instance of a duplicated command
setopt hist_ignore_dups       # Ignore duplicates when searching history
setopt hist_find_no_dups      # Do not display duplicates when searching history

# Load and initialize completion system
autoload -U compinit && compinit
# Configure case-insensitive completion matching
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# Customize completion menu selection behavior
zstyle ':completion:*' menu select

# Show git branch in prompt
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats '%B%F{yellow}git:(%F{202} %b %f%F{yellow}) %f'
setopt PROMPT_SUBST
PROMPT='%B%F{cyan} %1~%f%b $vcs_info_msg_0_$ '


export FZF_DEFAULT_COMMAND='fd --type f  --hidden --follow --exclude .git'
export FZF_CTRL_R_OPTS="
                      --preview 'echo {}' --preview-window up:3:hidden:wrap
                      --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
                      --header 'Press CTRL-Y to copy command into clipboard'"
# Print tree structure in the preview window
export FZF_ALT_C_COMMAND='fd --type d  --hidden --follow --exclude .git'
export FZF_ALT_C_OPTS="--preview 'tree -C {}'"


# Editor and grep settings
export EDITOR='nvim'
export GREP_OPTIONS='--color=always'
alias cat='bat -pp --color=always'
alias v='nvim'

# List colors for ls command
# Uncomment next line if on Mac
# alias ls="command ls -G"
export CLICOLOR=1
alias lsd="ls -lF -G | grep --color=never '^d'"

# Directory navigation aliases
alias .="cd .."
alias ..="cd ../.."
alias ...="cd ../../.."
alias ....="cd ../../../.."
alias cd..="cd .." # Typo addressed

# Other aliases and configurations
alias curl='curlie'


# warning: only include on mac
# Load syntax highlighting (for Mac)
source $HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# bacward fuzzy search => run on install
# $HOMEBREW_PREFIX/opt/fzf/install


################################################################################
# Colours

# Generated using https://dom111.github.io/grep-colors
GREP_COLORS='sl=49;39:cx=49;39:mt=49;31;1:fn=49;32:ln=49;33:bn=49;33:se=1;36'
#GREP_OPTIONS='--color=auto' # Deprecated

# Generated by hand, referencing http://linux-sxs.org/housekeeping/lscolors.html
# and https://geoff.greer.fm/lscolors/
LS_COLORS='di=1;34:ln=1;30;47:so=30;45:pi=30;45:ex=1;31:bd=30;46:cd=30;46:su=30'
LS_COLORS="${LS_COLORS};41:sg=30;41:tw=30;41:ow=30;41:*.rpm=1;31:*.deb=1;31"
LSCOLORS=ExahafafBxagagabababab

export GREP_COLORS LS_COLORS LSCOLORS

# Check for dircolors and if found, process .dircolors
# This sets up colours for 'ls' via LS_COLORS
if [[ -z "${LS_COLORS}" ]] && get_command dircolors; then
  if [[ -r ~/.dircolors ]]; then
    eval "$(dircolors -b ~/.dircolors)"
  elif [[ -r /etc/DIR_COLORS ]] ; then
    eval "$(dircolors -b /etc/DIR_COLORS)"
  else
    eval "$(dircolors -b)"
  fi
fi

LESS_TERMCAP_mb=$'\E[01;31m'
LESS_TERMCAP_md=$'\E[01;38;5;74m'
LESS_TERMCAP_me=$'\E[0m'
LESS_TERMCAP_se=$'\E[0m'
LESS_TERMCAP_so=$'\E[38;5;246m'
LESS_TERMCAP_ue=$'\E[0m'
LESS_TERMCAP_us=$'\E[04;38;5;146m'
export LESS_TERMCAP_mb LESS_TERMCAP_md LESS_TERMCAP_me LESS_TERMCAP_se
export LESS_TERMCAP_so LESS_TERMCAP_ue LESS_TERMCAP_us

echo "zsh config loaded"
