#!/bin/zsh
# Install zsh-autosuggestions
if [ ! -d "$HOME/.zsh/zsh-autosuggestions" ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions $HOME/.zsh/zsh-autosuggestions
fi
    source $HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

if [ -z "$TMUX" ]
then
    tmux attach -t TMUX || tmux new -s TMUX
fi

bindkey '^ ' autosuggest-accept

set_opacity() {
  if [[ -n "$1" ]]; then
    alacritty msg config "window.opacity=$1"
  else
    echo "Usage: set_opacity <value>"
  fi
}

# Configure command history settings
HISTSIZE=5000                 # Set maximum number of lines in history
HISTFILE=~/.zsh_history       # Define the location of the history file
SAVEHIST=5000                 # Save 5000 lines of history to the file
HISTDUP=erase                 # Remove duplicates in history
setopt appendhistory          # Append new history lines to the history file
setopt sharehistory           # Share history among all sessions
setopt incappendhistory       # Immediately append new lines to the history file
setopt hist_ignore_all_dups   # Ignore all duplicated commands in history
setopt hist_save_no_dups      # Save only the most recent instance of a duplicated command
setopt hist_ignore_dups       # Ignore duplicates when searching history
setopt hist_find_no_dups      # Do not display duplicates when searching history

# Enable case-insensitive completion
autoload -U compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

zstyle ':completion:*' menu select

#Show git branch in PROMPT
# Load version control information
autoload -Uz vcs_info
precmd() { vcs_info }

# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats '%B%F{yellow}git:(%F{red} %b %f%F{yellow})%f'
setopt PROMPT_SUBST
RPROMPT=\$vcs_info_msg_0_

PROMPT='%B%F{green}%n%f%b %B%F{cyan}%1~%f%b $ '

# FZF
export FZF_DEFAULT_OPTS="--preview 'bat -n --color=always {}' \
                        --multi \
                        --bind 'ctrl-v:execute(nvim {+})+abort,ctrl-p:toggle-preview,ctrl-y:execute-silent(echo {} | pbcopy)'"

export FZF_DEFAULT_COMMAND='fd --type f  --hidden --follow --exclude .git'

# Preview file content using bat (https://github.com/sharkdp/bat)
export FZF_CTRL_T_OPTS="
  --preview 'bat -n --color=always {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"
  
# CTRL-/ to toggle small preview window to see the full command
# CTRL-Y to copy the command into clipboard using pbcopy
export FZF_CTRL_R_OPTS="
  --preview 'echo {}' --preview-window up:3:hidden:wrap
  --bind 'ctrl-p:toggle-preview'
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"

# Print tree structure in the preview window
export FZF_ALT_C_OPTS="--preview 'tree -C {}'"

bindkey -s "^f" 'fzf^M'
alias f="fzf"

fzfcd() {
    local dir
    dir=$(fd --type d --hidden | fzf --preview 'tree -C {}')
    
    if [ -n "$dir" ]; then
        cd "$dir" || return
    fi
}
alias F="fzfcd"

export EDITOR='nvim'
export GREP_OPTIONS='--color=always'

alias cat='bat -pp --color=always'
alias v='nvim'

alias ls="command ls -G"

# List only directories
alias lsd="ls -lF -G | grep --color=never '^d'"

# Easier directory navigation.
alias .="cd .."
alias ..="cd ../.."
alias ...="cd ../../.."
alias ....="cd ../../../.."
alias cd..="cd .." # Typo addressed.
alias C="clear"


alias curl='curlie'


# warning: only include on mac
# Load syntax highlighting
source $HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# install for bacward fuzzy search
# warning: only run one time 
# $HOMEBREW_PREFIX/opt/fzf/install

################################################################################
# Colours

# Generated using https://dom111.github.io/grep-colors
GREP_COLORS='sl=49;39:cx=49;39:mt=49;31;1:fn=49;32:ln=49;33:bn=49;33:se=1;36'
#GREP_OPTIONS='--color=auto' # Deprecated

# Generated by hand, referencing http://linux-sxs.org/housekeeping/lscolors.html
# and https://geoff.greer.fm/lscolors/
LS_COLORS='di=1;34:ln=1;30;47:so=30;45:pi=30;45:ex=1;31:bd=30;46:cd=30;46:su=30'
LS_COLORS="${LS_COLORS};41:sg=30;41:tw=30;41:ow=30;41:*.rpm=1;31:*.deb=1;31"
LSCOLORS=ExahafafBxagagabababab

export GREP_COLORS LS_COLORS LSCOLORS

# Check for dircolors and if found, process .dircolors
# This sets up colours for 'ls' via LS_COLORS
if [[ -z "${LS_COLORS}" ]] && get_command dircolors; then
  if [[ -r ~/.dircolors ]]; then
    eval "$(dircolors -b ~/.dircolors)"
  elif [[ -r /etc/DIR_COLORS ]] ; then
    eval "$(dircolors -b /etc/DIR_COLORS)"
  else
    eval "$(dircolors -b)"
  fi
fi

LESS_TERMCAP_mb=$'\E[01;31m'
LESS_TERMCAP_md=$'\E[01;38;5;74m'
LESS_TERMCAP_me=$'\E[0m'
LESS_TERMCAP_se=$'\E[0m'
LESS_TERMCAP_so=$'\E[38;5;246m'
LESS_TERMCAP_ue=$'\E[0m'
LESS_TERMCAP_us=$'\E[04;38;5;146m'
export LESS_TERMCAP_mb LESS_TERMCAP_md LESS_TERMCAP_me LESS_TERMCAP_se
export LESS_TERMCAP_so LESS_TERMCAP_ue LESS_TERMCAP_us

echo "zsh config loaded"
