#!/usr/bin/env bash

RG_PREFIX="rga --files-with-matches"
DIR_LIST="~/notes ~/dev"
local file
file="$(
    FZF_DEFAULT_COMMAND="$RG_PREFIX '$1' $DIR_LIST" \
        fzf --sort --preview="[[ ! -z {} ]] && rga --pretty --context 5 {q} {}" \
            --phony -q "$1" \
            --bind "change:reload:$RG_PREFIX {q}  $DIR_LIST" \
            --preview-window="70%:wrap"
)" &&
echo "opening $file" &&
open "$file"
