#!/bin/bash

tmux new-window '
    selected_files=$( fd . ~/.config ~/dev --type f --hidden --exclude .git | fzf --preview "bat -n --color=always {}" )
    if [ -z "$selected_files" ]; then
        exit 0
    else nvim $selected_files
    fi
'
