# Install zsh-autosuggestions
if [ ! -d "$HOME/.zsh/zsh-autosuggestions" ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions $HOME/.zsh/zsh-autosuggestions
fi
    source $HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# Install zsh-fast-syntax-highlighting
if [ ! -d "$HOME/.zsh/fast-syntax-highlighting" ]; then
    git clone https://github.com/zdharma-continuum/fast-syntax-highlighting $HOME/.zsh/fast-syntax-highlighting
fi
    source $HOME/.zsh/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

# history
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=5000
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt incappendhistory
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups


#Case insensitive completion
autoload -U compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'


# Load version control information
autoload -Uz vcs_info
precmd() { vcs_info }

# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats '%F{red}%b%f'
setopt PROMPT_SUBST
RPROMPT=\$vcs_info_msg_0_

PROMPT='%F{cyan}%n%f %B%F{blue}%1~%f%b $ '

